### ISSUE TITLE
Dead link in README.rst

### ISSUE THREAD

**Issue by lumpidu** [mideind/GreynirCorrect#8]
> GreynirCorrect is documented in detail here.

The given link in [README.rst](https://github.com/mideind/GreynirCorrect/blob/master/README.rst) is dead.

**Comment by vthorsteinsson** [comment]
Thanks @lumpidu - confirmed bug, we'll look into it ASAP!

**Comment by vthorsteinsson** [comment]
Should be fixed now - was a regression in the web config file for yfirlestur.is.
